#include <glib.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <qrencode.h>
#include <stdio.h>
#include <stdint.h>
#include <string.h>

static const char *input = "f0VMRgIBAQAAAAAAAAAAAAIAPgABAAAACwJCAAAAAABAAAAAAAAAALiNDwAAAAAAAAAAAEAAOAAJAEAAHAAbAAYAAAAFAAAAQAAAAAAAAABAAEAAAAAAAEAAQAAAAAAA+AEAAAAAAAD4AQAAAAAAAAgAAAAAAAAAAwAAAAQAAAA4AgAAAAAAADgCQAAAAAAAOAJAAAAAAAAcAAAAAAAAABwAAAAAAAAAAQAAAAAAAAABAAAABQAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAANzvDgAAAAAA3O8OAAAAAAAAACAAAAAAAAEAAAAGAAAA8P0OAAAAAADw/W4AAAAAAPD9bgAAAAAAuI4AAAAAAACo6gAAAAAAAAAAIAAAAAAAAgAAAAYAAAAI/g4AAAAAAAj+bgAAAAAACP5uAAAAAADwAQAAAAAAAPABAAAAAAAACAAAAAAAAAAEAAAABAAAAFQCAAAAAAAAVAJAAAAAAABUAkAAAAAAAEQAAAAAAAAARAAAAAAAAAAEAAAAAAAAAFDldGQEAAAAsDwNAAAAAACwPE0AAAAAALA8TQAAAAAADEAAAAAAAAAMQAAAAAAAAAQAAAAAAAAAUeV0ZAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAABS5XRkBAAAAPD9DgAAAAAA8P1uAAAAAADw/W4AAAAAABACAAAAAAAAEAIAAAAAAAABAAAAAAAAAC9saWI2NC9sZC1saW51eC14ODYtNjQuc28uMgAEAAAAEAAAAAEAAABHTlUAAAAAAAIAAAAGAAAAGAAAAAQAAAAUAAAAAwAAAEdOVQBUlngi2gJ0Z/IeZaHqx1dt7H3YIQUIAADXAAAAAAEAAA4AAAAJMDACDAAAAAQjIUoFBQAEOEQSgpDBUE3gAEREAEIgEgAAAgAQBIAAAAkBgIAAQPAAFQBBAxJKjIEhEAtoBMRNAAg1ABwIYQEABiIAcoAKNgAIgggSAAFOTOYZQEBCpkEEQgAKEIAwikmkiYBwgSiiAgAFBmgFCAkAAAAAKACIkQxIIBsrEQQASCYSwoAQAEQAIRJEIAsAHIEABMAAICRESoCAgAhQYAYKlCAEAxAWBkBBBRCENBBgjghAEkFDAABkIABMQAgAAIgwIAFkkFCQQ0QEQhmAQKAWkAhBACUgAxAyADJCsFiIBACAAkAUQsoAAAAAAAAAAAjEAsMQRCSWEAEgCpACHpUCQAggQEEFAAGUJQAKiggUAAAAAAACoAEQMGAwIAkAAICQsAhoBAAAAAAICEADQAAgwGKIEAFCABFoC0hCoUgAmIETRBDBYDEAAUKCAg2QW3EBALAEQIgYFBAAghzJBhIggwCOWQoBQhhkSADgKAEwkBgQIkBCMRJAAwAAggAMcIQIAAAiDEERBFADAKiBkgACqhAQBJw4QAgBDSBzpDAgBZEiqpNCFCnSAyQIDgABHwGAEAQCJAEAREahABgwIswCEAgEkCAWAAEpNBAAlATB4aAkCEAAAYcARCCsAVgIEKiZEEEAhBAAIAICQAKAQjgyIBYIQkgUgIsQIIABgBggzCaK2A09AMBIAWRMQAGChKAwgSgQIAJwREBrQgFEEYZ0SGCBJHloAgbSQCiAgD4UhRUAwRIEgPiIqZACIAGoBvscAgFAIaQAJSkgUARIhICQoAEKYgJQEcFBAGJCkAAIDpQAFgARUECKKAIABAgCAwLjTCAuBDS6ABFCQAAAJgEAAABKAYAEAEQwiBg4AAABYAuCUFBRCDBEAZEQhAAcgGBgDCCLAqBIAYQAlAAQQImiAVAzoBQwIQQAABCIEAAIGACBINwEQkwBASA5RSQSIYAAABEIKChCogBEQAQigkCACAFAAMQQINAQWERCgRUYEaQAhASAEFGCKLQKBGiMAECBiQSUACMABIoIAAM2BAAAAAFBAmCAALAALhABBCMoAAIQEAALGEUAAjgQsDDIRMOQUBEKIoQkYwB0UHAKDSkEhgAMBOAABIEsAQAgABBCAUmipEEAgACABEABAiAAADSIZDHDgWTQQUCKgCATEgANCgaKEeAQh0gCzTJgAU5SIGyUjDFDkSAdACI3JGFE4QACIUE4CAgACFAAX1ABBwCIAAMJgAhZkM+aEoVIAxIgEACJKAhCgSAxQBAYOwNomMiAQQhFbgjQBSLICkwBqiAg4EYAAgiIAACKIAEgixAJAgAAAAQAAkYUgEAiBACRYCUgQDBBBRuUAaFgAGuIDBDFEQIkJiPEFgABBCAAWjQBEiUIRIGqIoCI4GgSVhDCIwCCBAAABq5AAABAAGAIAACEQAACgENEAIUABAQAIAVGADskgEIgBwN/SAWgBMYoQaBABEABsFAMACCAAEACqEIEIEAQQKQJQIYIOQKAhiDIAAWGQARTRg1EDkSR1QEKAoQAzIAJQECQMAgQBAoJROEAABAIgiCSAADY0AACGBgATABEgI6CBG8JYhAAiAEBIEmsD8MsUIwoAIRVAIIAAAKAFWAADiGDIAadygMBSBAgRAABSgIESGFwNQYECIiQCUIjJR0oSAUQAQACAAUZAEIGBwgKQRiiiQgQiBQAwEAgRTzgAAkGFBEACgCCAIAAABMlrACgRAMBJBJABQAQIAkAU2iACowBAgEAE4gmEgABwBIgESLCBWDIFAUMINg4DQBCMAAyACYAAwIgAwrVA0BDBCB0UBAUIlSgCCCoGDDAGeEQ6lABAhoQDQgAAAEAAGUAIAmovQBAEBACCAEGohCEAICAiBBBE0aBKCRCIOACIQRYgXIGtWQOIBfAxU08uCAAghgUAAIiIPMEgRrIEAkAAISYIqEQJiJQASDF4AFIIYAQFWCAJQgQAGABEQQADIABJCKCgEETCAIBABQYAAADIAMBAGAJMAAACAABBhABAAAAGAAAA";

#define PIXWIDTH 3

int main (int argc, char *argv[]) {

	QRcode *qrcode = QRcode_encodeString8bit(input, 40, QR_ECLEVEL_L);

	printf("QR Code has width %d\n", qrcode->width);

	GdkPixbuf *pixbuf = gdk_pixbuf_new(GDK_COLORSPACE_RGB, FALSE, 8, qrcode->width * PIXWIDTH, qrcode->width * PIXWIDTH);
	int n_channels = gdk_pixbuf_get_n_channels(pixbuf);

	g_assert(gdk_pixbuf_get_colorspace(pixbuf) == GDK_COLORSPACE_RGB);
	g_assert(gdk_pixbuf_get_bits_per_sample(pixbuf) == 8);
	g_assert(!gdk_pixbuf_get_has_alpha(pixbuf));
	g_assert(n_channels == 3);

	int rowstride = gdk_pixbuf_get_rowstride(pixbuf);
	guchar *p, *pixels = gdk_pixbuf_get_pixels(pixbuf);

	int row, col, inner;
	for (row = 0; row < qrcode->width; row++) {
		for (col = 0; col < qrcode->width; col++) {
			uint8_t datum = qrcode->data[row * qrcode->width + col];
			if ((datum & 0x01) == 0) {
				for (inner = 0; inner < PIXWIDTH; inner++) {
					p = pixels + row * rowstride * PIXWIDTH + inner * rowstride + col * n_channels * PIXWIDTH;
					memset(p, 0xff, n_channels * PIXWIDTH);
				}
			}
		}
	}

	gdk_pixbuf_save(pixbuf, "output.png", "png", NULL, NULL);

	g_object_unref(pixbuf);

	QRcode_free(qrcode);

	printf("Hello\n");
	return 0;
}